// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package provisioner

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Endpoint *string `mapstructure:"endpoint" cty:"endpoint" hcl:"endpoint"`
	Key      *string `mapstructure:"key" cty:"key" hcl:"key"`
	Value    *string `mapstructure:"value" cty:"value" hcl:"value"`
	Method   *string `mapstructure:"method" cty:"method" hcl:"method"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"endpoint": &hcldec.AttrSpec{Name: "endpoint", Type: cty.String, Required: true},
		"key":      &hcldec.AttrSpec{Name: "key", Type: cty.String, Required: true},
		"value":    &hcldec.AttrSpec{Name: "value", Type: cty.String, Required: true},
		"method":    &hcldec.AttrSpec{Name: "method", Type: cty.String, Required: true},
	}
	return s
}
